import {DrawerListProps} from "@/helpers/drawerLists/DrawerListProps";

export const cDrawerList = [
    {
        id: 1,
        title: "1. Введение в C",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Основы синтаксиса",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Переменные",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Управляющие конструкции",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Функции",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Массивы",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Указатели",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Строки",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Структуры",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Динамическая память",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Файловый ввод-вывод",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Препроцессор",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Модульность и заголовочные файлы",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Библиотеки",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Работа с памятью",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Обработка ошибок",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Многопоточность",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Сетевые возможности",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Работа с временем",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Расширенные темы",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Лучшие практики",
        link: "",
        isHead: true,
        passed: false,
    },
    {
        id: 1,
        title: "1. Что дальше?",
        link: "",
        isHead: true,
        passed: false,
    },
];